---

- name: Update repositories cache and install "docker and pip3" packages
  apt:
    pkg:
      - python3-pip
      - docker.io
      - docker-compose
    update_cache: yes
    cache_valid_time: 600

- name: Enable Docker
  service:
    name: docker
    enabled: yes
    state: started

- include_tasks: dirs.yml
- include_tasks: sudo-watch-stack.yml
- include_tasks: grafana.yml
- include_tasks: alertmanager.yml
- include_tasks: pushgateway.yml


