---
- name: Create and start Pushgateway service
  docker_compose:
    project_name: sudowatch
    definition:
      version: '2'


      networks:
        sudowatch_watch-net:
          external: true

      services:

        pushgateway:
          image: prom/pushgateway:v1.3.1
          container_name: pushgateway
          restart: unless-stopped
          expose:
            - 9091
          networks:
            - sudowatch_watch-net

  register: output
  when: enable_pushgateway

- ansible.builtin.debug:
    var: output
  when: enable_pushgateway

- ansible.builtin.assert:
    that:
      - "pushgateway.pushgateway.state.running"
  when: enable_pushgateway
