route:
    {% if slack_webhook_url is defined %}
    receiver: 'slack'
    {% endif %}

receivers:
    {% if slack_webhook_url is defined %}
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ '{{' }} .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: {{ slack_channel_name }}
            api_url: '{{ slack_webhook_url }}'
    {% endif %}